### ISSUE TITLE
pre-commit broken

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry-graphql-django#230]
I cannot format with pre-commit as I get the error:

error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/alex/.cache/pre-commit/repo0_a3fqxh/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/home/alex/.cache/pre-commit/repo0_a3fqxh/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/alex/.cache/pre-commit/repo0_a3fqxh/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-63gc7orw/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-63gc7orw/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

**Comment by g-as** [comment]
See https://github.com/PyCQA/isort/releases/tag/5.12.0 or https://github.com/PyCQA/isort/releases/tag/5.11.5.

`isort` should be bumped in
```yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
```
