### ISSUE TITLE
Async get_queryset not supported when using query optimizer

### ISSUE THREAD

**Issue by moritz89** [strawberry-graphql/strawberry-graphql-django#255]
## Describe the Bug

When enabling the query optimizer extension and an `gql.django.type` uses an async `get_queryset` method, an error is thrown that 

    AttributeError: 'coroutine' object has no attribute '_result_cache'

Removing the optimizer extension resolves the issue.

## System Information

 - Operating system: Ubuntu 22.04
 - strawberry-django-plus: 2.4.0
 - strawberry-graphql: 0.177.1
 - strawberry-graphql-django: 0.9.4

## Additional Context

The type:

```
@gql.django.type(OrganizationUser, filters=OrganizationUserFilter)
class OrganizationUserGQLNode(relay.Node):
    organization: OrganizationGQLNode
    user: UserGQLNode
    created_at: gql.auto
    modified_at: gql.auto

    @classmethod
    async def get_queryset(cls, queryset: QuerySet[OrganizationUser], info: Info):
        return await OrganizationPermissions.afilter_viewable_or_member_of_by_org(
            queryset, info.context.request.scope["user"]
        )
```

The schema:

```
schema = gql.Schema(
    query=Query,
    mutation=Mutation,
    subscription=Subscription,
    extensions=[DjangoOptimizerExtension],
)

```

The backtrace:

```
ERROR | main | strawberry.execution.execute:156 | 'coroutine' object has no attribute '_result_cache'

GraphQL request:2:3
1 | {
2 |   allOrganizationUsers {
  |   ^
3 |     edges {
Traceback (most recent call last):
  File "/.../lib/python3.10/site-packages/graphql/execution/execute.py", line 521, in execute_field
    result = resolve_fn(source, info, **args)
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 617, in resolve
    ret = _next(root, info, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 597, in _resolver
    return _get_result_with_extensions(
  File "/.../lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 583, in extension_resolver
    return reduce(
  File "/.../lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 578, in wrapped_get_result
    return _get_result(
  File "/.../lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 539, in _get_result
    return field.get_result(
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 1024, in get_result
    return self.resolver(source, info, args, kwargs, nodes=nodes)
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 1048, in resolver
    nodes = cast(Node, field_type).resolve_nodes(info=info)
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/type.py", line 316, in <lambda>
    lambda *args, **kwargs: resolve_model_nodes(
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/utils/resolvers.py", line 359, in resolve_model_nodes
    qs = ext.optimize(qs, info=info)
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 651, in optimize
    return optimize(qs, info, config=config, store=store)
  File "/.../lib/python3.10/site-packages/strawberry_django_plus/optimizer.py", line 323, in optimize
    if qs._result_cache is not None:  # type: ignore
AttributeError: 'coroutine' object has no attribute '_result_cache'
Stack (most recent call last):
  File "/.../lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 1118, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/.../lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 135, in inner_run
    ).run()
  File "/.../lib/python3.10/site-packages/daphne/server.py", line 149, in run
    reactor.run(installSignalHandlers=self.signal_handlers)
  File "/.../lib/python3.10/site-packages/twisted/internet/asyncioreactor.py", line 255, in run
    self._asyncioEventloop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/.../lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 101, in __call__
    return await self.application(scope, receive, send)
  File "/.../lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/.../lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/.../lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/.../lib/python3.10/site-packages/channels/routing.py", line 116, in __call__
    return await application(
  File "/.../django_keycloak/middleware.py", line 208, in __call__
    return await self.inner(scope, receive, send)
  File "/.../lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/.../lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/.../lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/.../lib/python3.10/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
  File "/.../lib/python3.10/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/.../lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/.../lib/python3.10/site-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/.../lib/python3.10/site-packages/strawberry/channels/handlers/base.py", line 108, in dispatch
    await super().dispatch(message)
  File "/.../lib/python3.10/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/.../lib/python3.10/site-packages/channels/generic/http.py", line 81, in http_request
    await self.handle(b"".join(self.body))
  File "/.../lib/python3.10/site-packages/strawberry/channels/handlers/http_handler.py", line 89, in handle
    result = await self.post(body)
  File "/.../lib/python3.10/site-packages/strawberry/channels/handlers/http_handler.py", line 140, in post
    result = await self.execute(request_data)
  File "/.../lib/python3.10/site-packages/strawberry/channels/handlers/http_handler.py", line 169, in execute
    result = await self.schema.execute(
  File "/.../lib/python3.10/site-packages/strawberry/schema/schema.py", line 248, in execute
    result = await execute(
  File "/.../lib/python3.10/site-packages/strawberry/schema/execute.py", line 156, in execute
    process_errors(result.errors, execution_context)
```

**Comment by bellini666** [comment]
Hey @moritz89 ,

This is related to https://github.com/blb-ventures/strawberry-django-plus , so you should register it there.

Either way, what is happening here is that `get_queryset` is not supposed to be asynchronous. Note that you don't need to generate the queryset asynchronously, as it will only query the database once it gets executed, and both strawberry-graphql-django and strawberry-django-plus will ensure that it does in an async context.

Maybe your made it asynchronous because `afilter_viewable_or_member_of_by_org` is executing the queryset? In this case I would advise you to change it to avoid executing it and returning the queryset only

**Comment by moritz89** [comment]
Sorry about that. Posting the follow-up here: https://github.com/blb-ventures/strawberry-django-plus/issues/206
