### ISSUE TITLE
Printing the schema should be working when `IsAuthenticated` permissions is used

### ISSUE THREAD

**Issue by oleo65** [strawberry-graphql/strawberry-graphql-django#289]
## Describe the Bug

As context: I am finalizing my migration to the new `strawberry_django` version from `strawberry_django_plus`.

I have many nodes which rely on permission directives. The implementation works as expected during tests with the GraphiQL interface.

In the past, I created a custom view to have a simple endpoint to expose the whole schema to use in different projects. This endpoint stopped working now complaining about a missing attribute. I suspect that something might have got lost during the merge of the projects.

views.py
```python
from .schema.schema import schema

class ApiSchema(View):

    @method_decorator(never_cache)
    def get(self, request):
        """Returns the current GraphQL schema definition"""
        schema_json = str(schema)
        return HttpResponse(schema_json, content_type='application/json')
```

schema.py
```python
import strawberry
from strawberry_django.optimizer import DjangoOptimizerExtension
from strawberry_django_firebase_auth.extension import FirebaseAuthStrawberryExtension

schema = strawberry.Schema(query=Query, mutation=Mutation, extensions=[
    FirebaseAuthStrawberryExtension,
    DjangoOptimizerExtension,
])
```
(`FirebaseAuthStrawberryExtension` is a custom extension by me, disabling it does not fix the error.)

sample_model.py (truncated)
```python
from strawberry_django.permissions import IsAuthenticated

@strawberry.type
class BankDepotMutation:

    @strawberry.mutation(directives=[IsAuthenticated()])
    def create_bank_depot(self, info: Info, input: CreateBankDepotInput) -> BankDepotNode:
        pass
```

If any more context is needed I am happy to update the description.

## System Information

 - Operating system: Windows 11
 - Strawberry version (if applicable): 0.194.4

## Additional Context
<details>
<summary>StackTrace:</summary>

```
[09/Jul/2023 14:16:59] "GET /graphql/schema HTTP/1.1" 500 136531
Internal Server Error: /graphql/schema
Traceback (most recent call last):
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/repos/investor/Investor/graphql_api/views.py", line 14, in get
    schema_json = str(schema)
                  ^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/schema/schema.py", line 363, in as_str
    return print_schema(self)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 563, in print_schema
    types_printed = [_print_type(type_, schema, extras=extras) for type_ in types]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 563, in <listcomp>
    types_printed = [_print_type(type_, schema, extras=extras) for type_ in types]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 451, in _print_type
    return _print_object(type_, schema, extras=extras)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 375, in _print_object
    + print_fields(type_, schema, extras=extras)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 250, in print_fields
    + print_field_directives(strawberry_field, schema=schema, extras=extras)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 174, in print_field_directives
    return "".join(
           ^^^^^^^^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 174, in <genexpr>
    return "".join(
                  ^
  File "/home/ole/.local/share/virtualenvs/investor-L5E8CZGz/lib/python3.11/site-packages/strawberry/printer/printer.py", line 170, in <genexpr>
    for location in directive.__strawberry_directive__.locations  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IsAuthenticated' object has no attribute '__strawberry_directive__'
```
</details>

**Comment by bellini666** [comment]
Hi @oleo65 ,

The permissioning system was refactored into field extensions, as you can see explained in the [migration guide](https://blb-ventures.github.io/strawberry-django-plus/migration-guide/#5-permissions-refactored-to-use-field-extensions)

So, instead of `@strawberry.mutation(directives=[IsAuthenticated()])`, you should be using `@strawberry.mutation(extensions=[IsAuthenticated()])`

They work the same way, but the implementation was greatly simplified. They will even be printed as a schema directive just like before.

Let me know if this fixes the issue for you.

**Comment by oleo65** [comment]
Thank you for your blazing fast reply. 😃 

The docs have not been clear to me, but with your explanation it now makes sense. My problem is fixed and the schema is generated.

One more fix I had to apply was to remove the directive from a type, which seems to be not supported any more. I applied it to the corresponding connection, which semantically is not the same but works in my case.

before
```python
import strawberry
from strawberry_django.permissions import IsSuperuser

@strawberry.django.type(PrivacyRequest, directives=[IsSuperUser()])
class PrivacyRequestNode(ModelNode):
    user: strawberry.auto
    has_consented: strawberry.auto

@strawberry.type
class PrivacyRequestQuery:
    privacy_requests: strawberry.relay.ListConnection[PrivacyRequestNode] = strawberry.django.connection()
```

after
```python
@strawberry.django.type(PrivacyRequest)
class PrivacyRequestNode(ModelNode):
    user: strawberry.auto
    has_consented: strawberry.auto

@strawberry.type
class PrivacyRequestQuery:
    privacy_requests: strawberry.relay.ListConnection[PrivacyRequestNode] = strawberry.django.connection(extensions=[IsSuperuser()])
```

**Comment by bellini666** [comment]
Hey @oleo65 ,

I'm closing this since it seems to be solved. But if you think there's still something to be done, even from the documentation's side, let me know :)
