### ISSUE TITLE
TypeError: get_result() got multiple values for argument 'kwargs'

### ISSUE THREAD

**Issue by 2malh** [strawberry-graphql/strawberry-graphql-django#29]
Hey there,

I'm on the 'feature/class-api' branch and all my queries and mutations raise an exception:
```
Traceback (most recent call last):
File "/venv/lib/python3.9/site-packages/graphql/execution/execute.py", line 678, in complete_value_catching_error
completed = self.complete_value(
File "/venv/lib/python3.9/site-packages/graphql/execution/execute.py", line 745, in complete_value
raise result
File "/venv/lib/python3.9/site-packages/graphql/execution/execute.py", line 637, in resolve_field_value_or_error
result = resolve_fn(source, info, **args)
File "/venv/lib/python3.9/site-packages/strawberry/middleware.py", line 29, in resolve
result = next_(root, info, **kwargs)
File "/venv/lib/python3.9/site-packages/strawberry/field.py", line 265, in _resolver
result = self.get_result(_source, info=strawberry_info, kwargs=kwargs)
TypeError: get_result() got multiple values for argument 'kwargs'
```

Here's a very basic setup to reproduce:
```py
# types.py

import strawberry
import strawberry_django
from strawberry_django import auto, auth
from django.contrib.auth import get_user_model

User = get_user_model()

@strawberry.type
class Test:
  name: str = "Hello world"

@strawberry_django.type(User)
class User:
  username: auto
  first_name: auto
  last_name: auto
  email: auto
```

```py
# schema.py
import strawberry
import strawberry_django
from typing import List

from .types import (
  User,
  Test
 )

from .core import auth

@strawberry.type
class Query:

  # Trying to see if a non strawberry_django type works -> it doesn't
  test: Test = strawberry_django.field()

  # USER QUERIES
  me: User = auth.current_user()
  user: User = strawberry_django.field()
  users: List[User] = strawberry_django.field()
  

@strawberry.type
class Mutation:
  login: User = auth.login()
  logout = auth.logout()

schema = strawberry.Schema(query=Query, mutation=Mutation)
```

The only mutation which is not throwing an error is `logout`. Everything else returns the exception mentioned before.
What am I missing?

Thanks for your help!

**Comment by la4de** [comment]
Thanks for reporting this issue. There was breaking change in strawberry graphql package version 0.59.1. Fix pushed to feature/class-api branch.

Your code looks good. Please retry and let us know if you still have the issue.
