### ISSUE TITLE
Mutation filters not working

### ISSUE THREAD

**Issue by jaydensmith** [strawberry-graphql/strawberry-graphql-django#317]
When specifying a mutation filter as per the docs, the filter does not appear in the generated schema:

```python
@strawberry.type
class Mutation:
    updateFruits: List[Fruit] = mutations.update(FruitPartialInput, filters=FruitFilter)
    deleteFruits: List[Fruit] = mutations.delete(filters=FruitFilter)
```

 - Operating system:
 - Strawberry version (if applicable): 0.195.2

**Comment by bellini666** [comment]
Hey @jaydensmith ,

I just tested here and it worked correctly.

Do you have a minimal reproduction example for this?

**Comment by jaydensmith** [comment]
@bellini666 it took a lot of digging around. You must enable the following new `MUTATIONS_DEFAULT_HANDLE_ERRORS` setting:

```python
STRAWBERRY_DJANGO = {
    'MUTATIONS_DEFAULT_HANDLE_ERRORS': True
}
```

This causes the return type to be a `Union` type, not a `StrawberryList`. So the following returns false.

https://github.com/strawberry-graphql/strawberry-graphql-django/blob/4bc135853cfa7965d286a11e2fc1782d69669894/strawberry_django/fields/base.py#L117-L123

**Comment by jaydensmith** [comment]
@bellini666 aside from not being able to filter the mutation so it affects all items, it does raise an exception:

```
Traceback (most recent call last):
  File "/Users/jaydensmith/public_html/test/.virtualenv/lib/python3.10/site-packages/graphql/execution/execute.py", line 527, in await_result
    completed = self.complete_value(
  File "/Users/jaydensmith/public_html/test/.virtualenv/lib/python3.10/site-packages/graphql/execution/execute.py", line 612, in complete_value
    completed = self.complete_value(
  File "/Users/jaydensmith/public_html/test/.virtualenv/lib/python3.10/site-packages/graphql/execution/execute.py", line 644, in complete_value
    return self.complete_abstract_value(
  File "/Users/jaydensmith/public_html/test/.virtualenv/lib/python3.10/site-packages/graphql/execution/execute.py", line 796, in complete_abstract_value
    runtime_type = resolve_type_fn(result, info, return_type)  # type: ignore
  File "/Users/jaydensmith/public_html/test/.virtualenv/lib/python3.10/site-packages/strawberry/union.py", line 188, in _resolve_union_type
    raise WrongReturnTypeForUnion(info.field_name, str(type(root)))
strawberry.exceptions.WrongReturnTypeForUnion: The type "<class 'list'>" cannot be resolved for the field "updateInventoryItems" , are you using a strawberry.field?
```
